### ISSUE TITLE
Input icons don't change color correctly if an error occurs

### ISSUE THREAD

**Issue by AtilioA** [AtilioA/AlertaDoTesouro#32]
## Example:
![2022-05-13_00-16](https://user-images.githubusercontent.com/27153776/168204582-52677a90-64b0-4f9a-a520-c9487a79ca3e.png)
Invalid e-mail should cause `FiUser` (now `FiAtSign`) icon to go red.

## Steps to reproduce:
1. Load `SignUp` page (`/registrar`)
1. Place any character into any input field
1. Click submit button

**Comment by Henriquelay** [comment]
Apparently this is intended, as I see from testing this does happens when the input is not empty -- and only then, indicating it is a required input.

Should we keep going with the issue? [Unform's reference documentation](https://unform-rocketseat.vercel.app/guides/get-set-field-error) is lacking in depth.

![image](https://user-images.githubusercontent.com/37563861/171336854-07c253f7-a188-44d3-a5aa-626aade5d6f6.png)
![image](https://user-images.githubusercontent.com/37563861/171336916-c66d635c-957d-40ab-b50e-81d08c076b4f.png)
![image](https://user-images.githubusercontent.com/37563861/171336980-1e68d2f4-1c1b-4e27-bb07-d020b01e8897.png)

**Comment by AtilioA** [comment]
Closing in favour of JavaScripto Bullshito
